name: zap-full-security-scan
on:
  schedule:
    # Runs every day At 00:13
    - cron:  '13 00 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.1.0
      with:
        target: "https://techconnectweb.azurewebsites.net/"
